//Header Files
#include<iostream.h>
#include<conio.h>

/*
	# : Preprocessor
	#include : Preprocessor Directives Iostream.h

	iostream : Input/Output Stream  : stream-> flow of data

	Input: User Input Read : cin>>

	Output: Write Ouput on the Screen : cout<<

	endl: New Line

	conio : Console Input/Output

	Console: Output Screen  : clrcsr(); , getch();

*/

void main() //entry point
{
	clrscr(); //clear screen
	cout<<"Hello World";    //print output
	getch(); //get character

	//; --> terminate the statement
}